[project]
name = "ai-talentquest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "flask-session>=0.5.0",
    "groq>=0.31.0",
    "requests>=2.32.5",
]
